"""initial_schema

Revision ID: 84a0eef84745
Revises: 
Create Date: 2026-03-01 13:42:05.549687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84a0eef84745'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False, comment='Matches auth.users.id — set by the handle_new_user trigger'),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ivr_architectures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ivr_architectures_user_id'), 'ivr_architectures', ['user_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ivr_architecture_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('flow_script', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of steps, e.g. [{"step":1,"listen":"Bienvenido","action":"send_dtmf_1"}]'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ivr_architecture_id'], ['ivr_architectures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_ivr_architecture_id'), 'test_cases', ['ivr_architecture_id'], unique=False)
    op.create_table('test_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'ERROR', name='test_status'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('twilio_call_sid', sa.String(length=64), nullable=True, comment='Twilio CallSid for cross-referencing in Twilio Console'),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_executions_test_case_id'), 'test_executions', ['test_case_id'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('expected_text', sa.TEXT(), nullable=True),
    sa.Column('actual_transcription', sa.TEXT(), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Similarity/confidence percentage from Deepgram (0.00 – 100.00)'),
    sa.Column('action_taken', sa.VARCHAR(length=255), nullable=True, comment='e.g. "Sent DTMF: 2" or "Call terminated"'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['test_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_execution_id'), 'execution_logs', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_logs_execution_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index(op.f('ix_test_executions_test_case_id'), table_name='test_executions')
    op.drop_table('test_executions')
    op.drop_index(op.f('ix_test_cases_ivr_architecture_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_ivr_architectures_user_id'), table_name='ivr_architectures')
    op.drop_table('ivr_architectures')
    op.drop_table('profiles')
    # ### end Alembic commands ###
