"""rename_voice-provider

Revision ID: a6f141c8c7c7
Revises: abc123def456
Create Date: 2026-03-08 21:47:15.451639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f141c8c7c7'
down_revision: Union[str, Sequence[str], None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_executions', sa.Column('provider_call_sid', sa.String(length=64), nullable=True, comment='CallSid returned by the voice provider (Twilio, Vonage, etc.)'))
    op.drop_column('test_executions', 'twilio_call_sid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_executions', sa.Column('twilio_call_sid', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='Twilio CallSid for cross-referencing in Twilio Console'))
    op.drop_column('test_executions', 'provider_call_sid')
    # ### end Alembic commands ###
