"""add_full_call_transcript

Revision ID: ab19bfe53fbe
Revises: 040f82a2dd0b
Create Date: 2026-03-27 16:24:03.602460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab19bfe53fbe'
down_revision: Union[str, Sequence[str], None] = '040f82a2dd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_executions', sa.Column('full_call_transcript', sa.Text(), nullable=True, comment='Complete transcript of the entire call for debugging and audit purposes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_executions', 'full_call_transcript')
    # ### end Alembic commands ###
